version: "3.8"
services:
  droneguru:
    build: .
    container_name: droneguru_bot
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ./app:/app/app
    restart: unless-stopped
