services:
  droneguru:
    build: .
    container_name: droneguru_bot
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    restart: unless-stopped

volumes:
  OllamaModels:

