FROM python:3.10.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ffmpeg git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
       torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu \
       git+https://github.com/openai/whisper.git

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app/main.py"]
