FROM python:3.11.0-slim

# Обновляем пакеты, устанавливаем ffmpeg и git
RUN apt-get update && apt-get install -y ffmpeg git

# Устанавливаем pip, PyTorch CPU-версию и Whisper из репозитория
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir git+https://github.com/openai/whisper.git

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app/main.py"]

